spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    username: root
    password: csasc
server:
  port: 8080
mybatis:
  mapper-locations: classpath:com/csasc/dao/*xml
  type-aliases-package: com.csasc.dao