spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimeZone=GMT
    username: root
    password: csasc
    redis:
      host: localhost # Redis服务器地址
      database: -1 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      jedis:
        pool:
          max-active: 7 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -2ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 7 # 连接池中的最大空闲连接
          min-idle: -1 # 连接池中的最小空闲连接
      timeout: 2999ms # 连接超时时间（毫秒）


server:
  port: 8089

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml;classpath*:/mapper/*.xml #指定mapper.xml路径
  global-config:
    db-config:
      id-type: auto #全局默认主键类型设置为自增
  configuration:
    auto-mapping-behavior: partial #只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true #开启自动驼峰命名规则映射

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

